import = [
"~/.config/alacritty/themes/noirbuddy.toml",
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
opacity = 1
decorations = "buttonless"
padding = { x = 18 , y = 18 }

[scrolling]
history = 100000
multiplier = 3

[font]
size = 18 
normal = { family = "DankMono Nerd Font Mono", style = "Regular" }
italic = { style = "Italic" }
bold = { style = "Bold" }

[cursor]
blink_interval = 500
style = { shape = "Block", blinking = "Always" }

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "Back"
mods = "Alt"
chars = "\u001b\u007f"
